import type { Metadata } from "next";
import { Carter_One } from 'next/font/google';
import "./globals.css";

const carterOne = Carter_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-carter-one',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${carterOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
